# By Andrew Paradi | Source at https://github.com/andrewparadi/docker-uwaterloo

version: '2'
services:

  uwaterloo:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: andrewparadi/uwaterloo
